version: '3.1'

networks:
  gpt:
    external: true

services:
  server-qa:
    container_name: server-qa
    image: 'server-qa:dev'
    networks:
      - gpt
    environment:
      AUTH_CODE: ${AUTH_CODE}
      OPENAI_KEYS: ${OPENAI_KEYS}
    tty: true
    restart: always
